export const BackdropBank = {
    Arctic: 'Arctic',
    Baseball_1: 'Baseball 1',
    Baseball_2: 'Baseball 2',
    Basketball_1: 'Basketball 1',
    Basketball_2: 'Basketball 2',
    Beach_Malibu: 'Beach Malibu',
    Beach_Rio: 'Beach Rio',
    Bedroom_1: 'Bedroom 1',
    Bedroom_2: 'Bedroom 2',
    Bedroom_3: 'Bedroom 3',
    Bench_With_View: 'Bench With View',
    Blue_Sky: 'Blue Sky',
    Blue_Sky_2_: 'Blue Sky 2 ',
    Boardwalk: 'Boardwalk',
    Canyon: 'Canyon',
    Castle_1: 'Castle 1',
    Castle_2: 'Castle 2',
    Castle_3: 'Castle 3',
    Castle_4: 'Castle 4',
    Chalkboard: 'Chalkboard',
    Circles: 'Circles',
    City_With_Water: 'City With Water',
    Colorful_City: 'Colorful City',
    Concert: 'Concert',
    Desert: 'Desert',
    Farm: 'Farm',
    Field_At_Mit: 'Field At Mit',
    Flowers: 'Flowers',
    Forest: 'Forest',
    Galaxy: 'Galaxy',
    Gardenrock: 'Garden-rock',
    Greek_Theater: 'Greek Theater',
    Hall: 'Hall',
    Hay_Field: 'Hay Field',
    Hearts: 'Hearts',
    Hill: 'Hill',
    Jungle: 'Jungle',
    Jurassic: 'Jurassic',
    Light: 'Light',
    Metro: 'Metro',
    Moon: 'Moon',
    Mountain: 'Mountain',
    Mural: 'Mural',
    Nebula: 'Nebula',
    Neon_Tunnel: 'Neon Tunnel',
    Night_City: 'Night City',
    Night_City_With_Street: 'Night City With Street',
    Party: 'Party',
    Pathway: 'Pathway',
    Playground: 'Playground',
    Playing_Field: 'Playing Field',
    Pool: 'Pool',
    Rays: 'Rays',
    Refrigerator: 'Refrigerator',
    Room_1: 'Room 1',
    Room_2: 'Room 2',
    Savanna: 'Savanna',
    School: 'School',
    Slopes: 'Slopes',
    Soccer: 'Soccer',
    Soccer_2: 'Soccer 2',
    Space: 'Space',
    Space_City_1: 'Space City 1',
    Space_City_2: 'Space City 2',
    Spaceship: 'Spaceship',
    Spotlight: 'Spotlight',
    Stars: 'Stars',
    Stripes: 'Stripes',
    Theater: 'Theater',
    Theater_2: 'Theater 2',
    Tree: 'Tree',
    Underwater_1: 'Underwater 1',
    Underwater_2: 'Underwater 2',
    Urban: 'Urban',
    Wall_1: 'Wall 1',
    Wall_2: 'Wall 2',
    Water_And_Rocks: 'Water And Rocks',
    Wetland: 'Wetland',
    Winter: 'Winter',
    Witch_House: 'Witch House',
    Woods: 'Woods',
    Woods_And_Bench: 'Woods And Bench',
    Xygrid: 'Xy-grid',
    Xygrid20px: 'Xy-grid-20px',
    Xygrid30px: 'Xy-grid-30px',
} as const;
export type TypeBackdropBankKey = keyof typeof BackdropBank;
export type TypeBackdropBankVal = typeof BackdropBank[TypeBackdropBankKey];