export const CostumeBank = {
    Abbya: 'Abby-a',
    Abbyb: 'Abby-b',
    Abbyc: 'Abby-c',
    Abbyd: 'Abby-d',
    Amon: 'Amon',
    Andiea: 'Andie-a',
    Andieb: 'Andie-b',
    Andiec: 'Andie-c',
    Andied: 'Andie-d',
    Anina_Pop_Down: 'Anina Pop Down',
    Anina_Pop_Front: 'Anina Pop Front',
    Anina_Pop_L_Arm: 'Anina Pop L Arm',
    Anina_Pop_Left: 'Anina Pop Left',
    Anina_Pop_R_Arm: 'Anina Pop R Arm',
    Anina_Pop_Right: 'Anina Pop Right',
    Anina_Pop_Stand: 'Anina Pop Stand',
    Anina_R_Cross: 'Anina R Cross',
    Anina_Stance: 'Anina Stance',
    Anina_Top_Freeze: 'Anina Top Freeze',
    Anina_Top_L_Step: 'Anina Top L Step',
    Anina_Top_R_Step: 'Anina Top R Step',
    Anina_Top_Stand: 'Anina Top Stand',
    Apple: 'Apple',
    Arrow1a: 'Arrow1-a',
    Arrow1b: 'Arrow1-b',
    Arrow1c: 'Arrow1-c',
    Arrow1d: 'Arrow1-d',
    Avery_Walkinga: 'Avery Walking-a',
    Avery_Walkingb: 'Avery Walking-b',
    Avery_Walkingc: 'Avery Walking-c',
    Avery_Walkingd: 'Avery Walking-d',
    Averya: 'Avery-a',
    Averyb: 'Avery-b',
    Balla: 'Ball-a',
    Ballb: 'Ball-b',
    Ballc: 'Ball-c',
    Balld: 'Ball-d',
    Balle: 'Ball-e',
    Ballerinaa: 'Ballerina-a',
    Ballerinab: 'Ballerina-b',
    Ballerinac: 'Ballerina-c',
    Ballerinad: 'Ballerina-d',
    Balloon1a: 'Balloon1-a',
    Balloon1b: 'Balloon1-b',
    Balloon1c: 'Balloon1-c',
    Bananas: 'Bananas',
    Baseball: 'Baseball',
    Basketball: 'Basketball',
    Bata: 'Bat-a',
    Batb: 'Bat-b',
    Batc: 'Bat-c',
    Batd: 'Bat-d',
    Battera: 'Batter-a',
    Batterb: 'Batter-b',
    Batterc: 'Batter-c',
    Batterd: 'Batter-d',
    Beachball: 'Beachball',
    Beara: 'Bear-a',
    Bearb: 'Bear-b',
    Bearwalka: 'Bear-walk-a',
    Bearwalkb: 'Bear-walk-b',
    Bearwalkc: 'Bear-walk-c',
    Bearwalkd: 'Bear-walk-d',
    Bearwalke: 'Bear-walk-e',
    Bearwalkf: 'Bear-walk-f',
    Bearwalkg: 'Bear-walk-g',
    Bearwalkh: 'Bear-walk-h',
    Beetle: 'Beetle',
    Bell1: 'Bell1',
    Bena: 'Ben-a',
    Benb: 'Ben-b',
    Benc: 'Ben-c',
    Bend: 'Ben-d',
    Bowla: 'Bowl-a',
    Bowtie: 'Bowtie',
    Bread: 'Bread',
    Broom: 'Broom',
    Buildinga: 'Building-a',
    Buildingb: 'Building-b',
    Buildingc: 'Building-c',
    Buildingd: 'Building-d',
    Buildinge: 'Building-e',
    Buildingf: 'Building-f',
    Buildingg: 'Building-g',
    Buildingh: 'Building-h',
    Buildingi: 'Building-i',
    Buildingj: 'Building-j',
    Butterfly1a: 'Butterfly1-a',
    Butterfly1b: 'Butterfly1-b',
    Butterfly1c: 'Butterfly1-c',
    Butterfly2a: 'Butterfly2-a',
    Butterfly2b: 'Butterfly2-b',
    Button1: 'Button1',
    Button2a: 'Button2-a',
    Button2b: 'Button2-b',
    Button3a: 'Button3-a',
    Button3b: 'Button3-b',
    Button4a: 'Button4-a',
    Button4b: 'Button4-b',
    Button5a: 'Button5-a',
    Button5b: 'Button5-b',
    Cakea: 'Cake-a',
    Cakeb: 'Cake-b',
    Calvrett_Jumping: 'Calvrett Jumping',
    Calvrett_Thinking: 'Calvrett Thinking',
    Caseya: 'Casey-a',
    Caseyb: 'Casey-b',
    Caseyc: 'Casey-c',
    Caseyd: 'Casey-d',
    Cassya: 'Cassy-a',
    Cassyb: 'Cassy-b',
    Cassyc: 'Cassy-c',
    Cassyd: 'Cassy-d',
    Cat_2: 'Cat 2',
    Cat_Flyinga: 'Cat Flying-a',
    Cat_Flyingb: 'Cat Flying-b',
    Cata: 'Cat-a',
    Catb: 'Cat-b',
    Catchera: 'Catcher-a',
    Catcherb: 'Catcher-b',
    Catcherc: 'Catcher-c',
    Catcherd: 'Catcher-d',
    Centaura: 'Centaur-a',
    Centaurb: 'Centaur-b',
    Centaurc: 'Centaur-c',
    Centaurd: 'Centaur-d',
    Champ99a: 'Champ99-a',
    Champ99b: 'Champ99-b',
    Champ99c: 'Champ99-c',
    Champ99d: 'Champ99-d',
    Champ99e: 'Champ99-e',
    Champ99f: 'Champ99-f',
    Champ99g: 'Champ99-g',
    Character1a: 'Character1-a',
    Character1b: 'Character1-b',
    Character1c: 'Character1-c',
    Character1d: 'Character1-d',
    Character1e: 'Character1-e',
    Character1f: 'Character1-f',
    Character1g: 'Character1-g',
    Character1h: 'Character1-h',
    Character1i: 'Character1-i',
    Character1j: 'Character1-j',
    Character1k: 'Character1-k',
    Character1l: 'Character1-l',
    Character1m: 'Character1-m',
    Character2a: 'Character2-a',
    Character2b: 'Character2-b',
    Character2c: 'Character2-c',
    Character2d: 'Character2-d',
    Character2e: 'Character2-e',
    Character2f: 'Character2-f',
    Character2g: 'Character2-g',
    Character2h: 'Character2-h',
    Character2i: 'Character2-i',
    Character2j: 'Character2-j',
    Cheesy_Puffs: 'Cheesy Puffs',
    Chicka: 'Chick-a',
    Chickb: 'Chick-b',
    Chickc: 'Chick-c',
    City_Busa: 'City Bus-a',
    City_Busb: 'City Bus-b',
    Cloud: 'Cloud',
    Clouda: 'Cloud-a',
    Cloudb: 'Cloud-b',
    Cloudc: 'Cloud-c',
    Cloudd: 'Cloud-d',
    Convertible: 'Convertible',
    Convertible_3: 'Convertible 3',
    Craba: 'Crab-a',
    Crabb: 'Crab-b',
    Crystala: 'Crystal-a',
    Crystalb: 'Crystal-b',
    Dana: 'Dan-a',
    Danb: 'Dan-b',
    Dania: 'Dani-a',
    Danib: 'Dani-b',
    Danic: 'Dani-c',
    Deea: 'Dee-a',
    Deeb: 'Dee-b',
    Deec: 'Dee-c',
    Deed: 'Dee-d',
    Deee: 'Dee-e',
    Devina: 'Devin-a',
    Devinb: 'Devin-b',
    Devinc: 'Devin-c',
    Devind: 'Devin-d',
    Dinosaur1a: 'Dinosaur1-a',
    Dinosaur1b: 'Dinosaur1-b',
    Dinosaur1c: 'Dinosaur1-c',
    Dinosaur1d: 'Dinosaur1-d',
    Dinosaur2a: 'Dinosaur2-a',
    Dinosaur2b: 'Dinosaur2-b',
    Dinosaur2c: 'Dinosaur2-c',
    Dinosaur2d: 'Dinosaur2-d',
    Dinosaur3a: 'Dinosaur3-a',
    Dinosaur3b: 'Dinosaur3-b',
    Dinosaur3c: 'Dinosaur3-c',
    Dinosaur3d: 'Dinosaur3-d',
    Dinosaur3e: 'Dinosaur3-e',
    Dinosaur4a: 'Dinosaur4-a',
    Dinosaur4b: 'Dinosaur4-b',
    Dinosaur4c: 'Dinosaur4-c',
    Dinosaur4d: 'Dinosaur4-d',
    Diver1: 'Diver1',
    Diver2: 'Diver2',
    Dm_Freeze: 'Dm Freeze',
    Dm_Pop_Down: 'Dm Pop Down',
    Dm_Pop_Front: 'Dm Pop Front',
    Dm_Pop_L_Arm: 'Dm Pop L Arm',
    Dm_Pop_Left: 'Dm Pop Left',
    Dm_Pop_R_Arm: 'Dm Pop R Arm',
    Dm_Pop_Right: 'Dm Pop Right',
    Dm_Pop_Stand: 'Dm Pop Stand',
    Dm_Stance: 'Dm Stance',
    Dm_Top_L_Leg: 'Dm Top L Leg',
    Dm_Top_R_Leg: 'Dm Top R Leg',
    Dm_Top_Stand: 'Dm Top Stand',
    Dog1a: 'Dog1-a',
    Dog1b: 'Dog1-b',
    Dog2a: 'Dog2-a',
    Dog2b: 'Dog2-b',
    Dog2c: 'Dog2-c',
    Donut: 'Donut',
    Doriana: 'Dorian-a',
    Dorianb: 'Dorian-b',
    Dorianc: 'Dorian-c',
    Doriand: 'Dorian-d',
    Dota: 'Dot-a',
    Dotb: 'Dot-b',
    Dotc: 'Dot-c',
    Dotd: 'Dot-d',
    Dovea: 'Dove-a',
    Doveb: 'Dove-b',
    Dragona: 'Dragon-a',
    Dragonb: 'Dragon-b',
    Dragonc: 'Dragon-c',
    Dragon1a: 'Dragon1-a',
    Dragon1b: 'Dragon1-b',
    Dragonflya: 'Dragonfly-a',
    Dragonflyb: 'Dragonfly-b',
    Dressa: 'Dress-a',
    Dressb: 'Dress-b',
    Dressc: 'Dress-c',
    Druma: 'Drum-a',
    Drumb: 'Drum-b',
    Drumcymbala: 'Drum-cymbal-a',
    Drumcymbalb: 'Drum-cymbal-b',
    Drumhighhata: 'Drum-highhat-a',
    Drumhighhatb: 'Drum-highhat-b',
    Drumkit: 'Drum-kit',
    Drumkitb: 'Drum-kit-b',
    Drumsnarea: 'Drum-snare-a',
    Drumsnareb: 'Drum-snare-b',
    Drums_Congaa: 'Drums Conga-a',
    Drums_Congab: 'Drums Conga-b',
    Duck: 'Duck',
    Earth: 'Earth',
    Easela: 'Easel-a',
    Easelb: 'Easel-b',
    Easelc: 'Easel-c',
    Egga: 'Egg-a',
    Eggb: 'Egg-b',
    Eggc: 'Egg-c',
    Eggd: 'Egg-d',
    Egge: 'Egg-e',
    Eggf: 'Egg-f',
    Elephanta: 'Elephant-a',
    Elephantb: 'Elephant-b',
    Elfa: 'Elf-a',
    Elfb: 'Elf-b',
    Elfc: 'Elf-c',
    Elfd: 'Elf-d',
    Elfe: 'Elf-e',
    Fairya: 'Fairy-a',
    Fairyb: 'Fairy-b',
    Fairyc: 'Fairy-c',
    Fairyd: 'Fairy-d',
    Fairye: 'Fairy-e',
    Fisha: 'Fish-a',
    Fishb: 'Fish-b',
    Fishc: 'Fish-c',
    Fishd: 'Fish-d',
    Fishbowla: 'Fishbowl-a',
    Fishbowlb: 'Fishbowl-b',
    Food_Trucka: 'Food Truck-a',
    Food_Truckb: 'Food Truck-b',
    Food_Truckc: 'Food Truck-c',
    Football_Running: 'Football Running',
    Football_Standing: 'Football Standing',
    Fortune_Cookie: 'Fortune Cookie',
    Foxa: 'Fox-a',
    Foxb: 'Fox-b',
    Foxc: 'Fox-c',
    Franka: 'Frank-a',
    Frankb: 'Frank-b',
    Frankc: 'Frank-c',
    Frankd: 'Frank-d',
    Frog: 'Frog',
    Frog_2a: 'Frog 2-a',
    Frog_2b: 'Frog 2-b',
    Frog_2c: 'Frog 2-c',
    Fruit_Platter: 'Fruit Platter',
    Fruitsalad: 'Fruitsalad',
    Ghosta: 'Ghost-a',
    Ghostb: 'Ghost-b',
    Ghostc: 'Ghost-c',
    Ghostd: 'Ghost-d',
    Gifta: 'Gift-a',
    Giftb: 'Gift-b',
    Giga_Walk1: 'Giga Walk1',
    Giga_Walk2: 'Giga Walk2',
    Giga_Walk3: 'Giga Walk3',
    Gigaa: 'Giga-a',
    Gigab: 'Giga-b',
    Gigac: 'Giga-c',
    Gigad: 'Giga-d',
    Giraffea: 'Giraffe-a',
    Giraffeb: 'Giraffe-b',
    Giraffec: 'Giraffe-c',
    Glass_Watera: 'Glass Water-a',
    Glass_Waterb: 'Glass Water-b',
    Glassesa: 'Glasses-a',
    Glassesb: 'Glasses-b',
    Glassesc: 'Glasses-c',
    Glassese: 'Glasses-e',
    Goaliea: 'Goalie-a',
    Goalieb: 'Goalie-b',
    Goaliec: 'Goalie-c',
    Goalied: 'Goalie-d',
    Goaliee: 'Goalie-e',
    Goblina: 'Goblin-a',
    Goblinb: 'Goblin-b',
    Goblinc: 'Goblin-c',
    Goblind: 'Goblin-d',
    Goboa: 'Gobo-a',
    Gobob: 'Gobo-b',
    Goboc: 'Gobo-c',
    Grasshoppera: 'Grasshopper-a',
    Grasshopperb: 'Grasshopper-b',
    Grasshopperc: 'Grasshopper-c',
    Grasshopperd: 'Grasshopper-d',
    Grasshoppere: 'Grasshopper-e',
    Grasshopperf: 'Grasshopper-f',
    Green_Flag: 'Green Flag',
    Griffina: 'Griffin-a',
    Griffinb: 'Griffin-b',
    Griffinc: 'Griffin-c',
    Griffind: 'Griffin-d',
    Guitara: 'Guitar-a',
    Guitarb: 'Guitar-b',
    Guitarelectric1a: 'Guitar-electric1-a',
    Guitarelectric1b: 'Guitar-electric1-b',
    Guitarelectric2a: 'Guitar-electric2-a',
    Guitarelectric2b: 'Guitar-electric2-b',
    Hannaha: 'Hannah-a',
    Hannahb: 'Hannah-b',
    Hannahc: 'Hannah-c',
    Harea: 'Hare-a',
    Hareb: 'Hare-b',
    Harec: 'Hare-c',
    Harpera: 'Harper-a',
    Harperb: 'Harper-b',
    Harperc: 'Harper-c',
    Hata: 'Hat-a',
    Hatb: 'Hat-b',
    Hatc: 'Hat-c',
    Hatd: 'Hat-d',
    Hatchlinga: 'Hatchling-a',
    Hatchlingb: 'Hatchling-b',
    Hatchlingc: 'Hatchling-c',
    Heart_Code: 'Heart Code',
    Heart_Face: 'Heart Face',
    Heart_Love: 'Heart Love',
    Heart_Purple: 'Heart Purple',
    Heart_Red: 'Heart Red',
    Heart_Smile: 'Heart Smile',
    Heart_Sweet: 'Heart Sweet',
    Hedgehoga: 'Hedgehog-a',
    Hedgehogb: 'Hedgehog-b',
    Hedgehogc: 'Hedgehog-c',
    Hedgehogd: 'Hedgehog-d',
    Hedgehoge: 'Hedgehog-e',
    Hena: 'Hen-a',
    Henb: 'Hen-b',
    Henc: 'Hen-c',
    Hend: 'Hen-d',
    Hippo1a: 'Hippo1-a',
    Hippo1b: 'Hippo1-b',
    Home_Button: 'Home Button',
    Horsea: 'Horse-a',
    Horseb: 'Horse-b',
    Jaime_Walkinga: 'Jaime Walking-a',
    Jaime_Walkingb: 'Jaime Walking-b',
    Jaime_Walkingc: 'Jaime Walking-c',
    Jaime_Walkingd: 'Jaime Walking-d',
    Jaime_Walkinge: 'Jaime Walking-e',
    Jaimea: 'Jaime-a',
    Jaimeb: 'Jaime-b',
    Jamala: 'Jamal-a',
    Jamalb: 'Jamal-b',
    Jamalc: 'Jamal-c',
    Jamald: 'Jamal-d',
    Jara: 'Jar-a',
    Jarb: 'Jar-b',
    Jellyfisha: 'Jellyfish-a',
    Jellyfishb: 'Jellyfish-b',
    Jellyfishc: 'Jellyfish-c',
    Jellyfishd: 'Jellyfish-d',
    Jo_Pop_Down: 'Jo Pop Down',
    Jo_Pop_Front: 'Jo Pop Front',
    Jo_Pop_L_Arm: 'Jo Pop L Arm',
    Jo_Pop_Left: 'Jo Pop Left',
    Jo_Pop_R_Arm: 'Jo Pop R Arm',
    Jo_Pop_Right: 'Jo Pop Right',
    Jo_Pop_Stand: 'Jo Pop Stand',
    Jo_Stance: 'Jo Stance',
    Jo_Top_L_Cross: 'Jo Top L Cross',
    Jo_Top_L_Leg: 'Jo Top L Leg',
    Jo_Top_R_Cross: 'Jo Top R Cross',
    Jo_Top_R_Leg: 'Jo Top R Leg',
    Jo_Top_Stand: 'Jo Top Stand',
    Jordyna: 'Jordyn-a',
    Jordynb: 'Jordyn-b',
    Jordync: 'Jordyn-c',
    Jordynd: 'Jordyn-d',
    Kaia: 'Kai-a',
    Kaib: 'Kai-b',
    Key: 'Key',
    Keyboarda: 'Keyboard-a',
    Keyboardb: 'Keyboard-b',
    Kiaa: 'Kia-a',
    Kiab: 'Kia-b',
    Kiac: 'Kia-c',
    Kirana: 'Kiran-a',
    Kiranb: 'Kiran-b',
    Kiranc: 'Kiran-c',
    Kirand: 'Kiran-d',
    Kirane: 'Kiran-e',
    Kiranf: 'Kiran-f',
    Knight: 'Knight',
    Ladybug2: 'Ladybug2',
    Ladybug2a: 'Ladybug2-a',
    Ladybug2b: 'Ladybug2-b',
    Laptop: 'Laptop',
    Lb_Pop_Down: 'Lb Pop Down',
    Lb_Pop_Front: 'Lb Pop Front',
    Lb_Pop_L_Arm: 'Lb Pop L Arm',
    Lb_Pop_Left: 'Lb Pop Left',
    Lb_Pop_R_Arm: 'Lb Pop R Arm',
    Lb_Pop_Right: 'Lb Pop Right',
    Lb_Pop_Stand: 'Lb Pop Stand',
    Lb_Stance: 'Lb Stance',
    Lb_Top_L_Cross: 'Lb Top L Cross',
    Lb_Top_L_Leg: 'Lb Top L Leg',
    Lb_Top_R_Cross: 'Lb Top R Cross',
    Lb_Top_R_Leg: 'Lb Top R Leg',
    Lb_Top_Stand: 'Lb Top Stand',
    Lightning: 'Lightning',
    Line: 'Line',
    Liona: 'Lion-a',
    Lionb: 'Lion-b',
    Lionc: 'Lion-c',
    Llama: 'Llama',
    Llamab: 'Llama-b',
    Llamac: 'Llama-c',
    Lucaa: 'Luca-a',
    Lucab: 'Luca-b',
    Lucac: 'Luca-c',
    Magicwand: 'Magicwand',
    Mariana: 'Marian-a',
    Marianb: 'Marian-b',
    Marianc: 'Marian-c',
    Mariand: 'Marian-d',
    Mariane: 'Marian-e',
    Maxa: 'Max-a',
    Maxb: 'Max-b',
    Maxc: 'Max-c',
    Maxd: 'Max-d',
    Mermaida: 'Mermaid-a',
    Mermaidb: 'Mermaid-b',
    Mermaidc: 'Mermaid-c',
    Mermaidd: 'Mermaid-d',
    Microphonea: 'Microphone-a',
    Microphoneb: 'Microphone-b',
    Milka: 'Milk-a',
    Milkb: 'Milk-b',
    Milkc: 'Milk-c',
    Milkd: 'Milk-d',
    Milke: 'Milk-e',
    Moneta: 'Monet-a',
    Monetb: 'Monet-b',
    Monetc: 'Monet-c',
    Monetd: 'Monet-d',
    Monete: 'Monet-e',
    Monkeya: 'Monkey-a',
    Monkeyb: 'Monkey-b',
    Monkeyc: 'Monkey-c',
    Motorcyclea: 'Motorcycle-a',
    Motorcycleb: 'Motorcycle-b',
    Motorcyclec: 'Motorcycle-c',
    Motorcycled: 'Motorcycle-d',
    Mouse1a: 'Mouse1-a',
    Mouse1b: 'Mouse1-b',
    Muffina: 'Muffin-a',
    Muffinb: 'Muffin-b',
    Nanoa: 'Nano-a',
    Nanob: 'Nano-b',
    Nanoc: 'Nano-c',
    Nanod: 'Nano-d',
    Neigh_Pony: 'Neigh Pony',
    Noora: 'Noor-a',
    Noorb: 'Noor-b',
    Noorc: 'Noor-c',
    Octopusa: 'Octopus-a',
    Octopusb: 'Octopus-b',
    Octopusc: 'Octopus-c',
    Octopusd: 'Octopus-d',
    Octopuse: 'Octopus-e',
    Orange: 'Orange',
    Orange2a: 'Orange2-a',
    Orange2b: 'Orange2-b',
    Outfieldera: 'Outfielder-a',
    Outfielderb: 'Outfielder-b',
    Outfielderc: 'Outfielder-c',
    Outfielderd: 'Outfielder-d',
    Owla: 'Owl-a',
    Owlb: 'Owl-b',
    Owlc: 'Owl-c',
    Paddle: 'Paddle',
    Panthera: 'Panther-a',
    Pantherb: 'Panther-b',
    Pantherc: 'Panther-c',
    Pantsa: 'Pants-a',
    Pantsb: 'Pants-b',
    Parrota: 'Parrot-a',
    Parrotb: 'Parrot-b',
    Party_Hata: 'Party Hat-a',
    Party_Hatb: 'Party Hat-b',
    Party_Hate: 'Party Hat-e',
    Pencila: 'Pencil-a',
    Pencilb: 'Pencil-b',
    Penguina: 'Penguin-a',
    Penguinb: 'Penguin-b',
    Penguinc: 'Penguin-c',
    Penguin2a: 'Penguin2-a',
    Penguin2b: 'Penguin2-b',
    Penguin2c: 'Penguin2-c',
    Penguin2d: 'Penguin2-d',
    Pico_Walk1: 'Pico Walk1',
    Pico_Walk2: 'Pico Walk2',
    Pico_Walk3: 'Pico Walk3',
    Pico_Walk4: 'Pico Walk4',
    Picoa: 'Pico-a',
    Picob: 'Pico-b',
    Picoc: 'Pico-c',
    Picod: 'Pico-d',
    Pitchera: 'Pitcher-a',
    Pitcherb: 'Pitcher-b',
    Pitcherc: 'Pitcher-c',
    Pitcherd: 'Pitcher-d',
    Planet2: 'Planet2',
    Polar_Beara: 'Polar Bear-a',
    Polar_Bearb: 'Polar Bear-b',
    Polar_Bearc: 'Polar Bear-c',
    Potiona: 'Potion-a',
    Potionb: 'Potion-b',
    Potionc: 'Potion-c',
    Prince: 'Prince',
    Princessa: 'Princess-a',
    Princessb: 'Princess-b',
    Princessc: 'Princess-c',
    Princessd: 'Princess-d',
    Princesse: 'Princess-e',
    Pufferfisha: 'Pufferfish-a',
    Pufferfishb: 'Pufferfish-b',
    Pufferfishc: 'Pufferfish-c',
    Pufferfishd: 'Pufferfish-d',
    Puppy_Back: 'Puppy Back',
    Puppy_Right: 'Puppy Right',
    Puppy_Side: 'Puppy Side',
    Puppy_Sit: 'Puppy Sit',
    Rabbita: 'Rabbit-a',
    Rabbitb: 'Rabbit-b',
    Rabbitc: 'Rabbit-c',
    Rabbitd: 'Rabbit-d',
    Rabbite: 'Rabbit-e',
    Radioa: 'Radio-a',
    Radiob: 'Radio-b',
    Rainbow: 'Rainbow',
    Refereea: 'Referee-a',
    Refereeb: 'Referee-b',
    Refereec: 'Referee-c',
    Refereed: 'Referee-d',
    Reindeer: 'Reindeer',
    Retro_Robot_A: 'Retro Robot A',
    Retro_Robot_B: 'Retro Robot B',
    Retro_Robot_C: 'Retro Robot C',
    Ripleya: 'Ripley-a',
    Ripleyb: 'Ripley-b',
    Ripleyc: 'Ripley-c',
    Ripleyd: 'Ripley-d',
    Ripleye: 'Ripley-e',
    Ripleyf: 'Ripley-f',
    Robota: 'Robot-a',
    Robotb: 'Robot-b',
    Robotc: 'Robot-c',
    Robotd: 'Robot-d',
    Rocketshipa: 'Rocketship-a',
    Rocketshipb: 'Rocketship-b',
    Rocketshipc: 'Rocketship-c',
    Rocketshipd: 'Rocketship-d',
    Rocketshipe: 'Rocketship-e',
    Rocks: 'Rocks',
    Roostera: 'Rooster-a',
    Roosterb: 'Rooster-b',
    Roosterc: 'Rooster-c',
    Rubya: 'Ruby-a',
    Rubyb: 'Ruby-b',
    Sailboat: 'Sailboat',
    Sam: 'Sam',
    Sashaa: 'Sasha-a',
    Sashab: 'Sasha-b',
    Sashac: 'Sasha-c',
    Saxophonea: 'Saxophone-a',
    Saxophoneb: 'Saxophone-b',
    Scarfa: 'Scarf-a',
    Scarfb: 'Scarf-b',
    Scarfc: 'Scarf-c',
    Sharka: 'Shark-a',
    Sharkb: 'Shark-b',
    Shark2a: 'Shark2-a',
    Shark2b: 'Shark2-b',
    Shark2c: 'Shark2-c',
    Shirta: 'Shirt-a',
    Shoesa: 'Shoes-a',
    Shoesb: 'Shoes-b',
    Shoesc: 'Shoes-c',
    Shoesd: 'Shoes-d',
    Shortsa: 'Shorts-a',
    Shortsb: 'Shorts-b',
    Shortsc: 'Shorts-c',
    Singer1: 'Singer1',
    Skeletona: 'Skeleton-a',
    Skeletonb: 'Skeleton-b',
    Skeletond: 'Skeleton-d',
    Skeletone: 'Skeleton-e',
    Snakea: 'Snake-a',
    Snakeb: 'Snake-b',
    Snakec: 'Snake-c',
    Snowflake: 'Snowflake',
    Snowman: 'Snowman',
    Soccer_Ball: 'Soccer Ball',
    Speaker: 'Speaker',
    Squirrel: 'Squirrel',
    Star: 'Star',
    Starfisha: 'Starfish-a',
    Starfishb_: 'Starfish-b ',
    Stop: 'Stop',
    Strawberrya: 'Strawberry-a',
    Strawberryb: 'Strawberry-b',
    Strawberryc: 'Strawberry-c',
    Strawberryd: 'Strawberry-d',
    Strawberrye: 'Strawberry-e',
    Sun: 'Sun',
    Sunglassesa: 'Sunglasses-a',
    Sunglassesb: 'Sunglasses-b',
    Tablaa: 'Tabla-a',
    Tablab: 'Tabla-b',
    Taco: 'Taco',
    Tacowizard: 'Taco-wizard',
    Takeouta: 'Takeout-a',
    Takeoutb: 'Takeout-b',
    Takeoutc: 'Takeout-c',
    Takeoutd: 'Takeout-d',
    Takeoute: 'Takeout-e',
    Tatianaa: 'Tatiana-a',
    Tatianab: 'Tatiana-b',
    Tatianac: 'Tatiana-c',
    Tatianad: 'Tatiana-d',
    Taylora: 'Taylor-a',
    Taylorb: 'Taylor-b',
    Taylorc: 'Taylor-c',
    Taylord: 'Taylor-d',
    Ten80_Pop_Down: 'Ten80 Pop Down',
    Ten80_Pop_Front: 'Ten80 Pop Front',
    Ten80_Pop_L_Arm: 'Ten80 Pop L Arm',
    Ten80_Pop_Left: 'Ten80 Pop Left',
    Ten80_Pop_R_Arm: 'Ten80 Pop R Arm',
    Ten80_Pop_Right: 'Ten80 Pop Right',
    Ten80_Pop_Stand: 'Ten80 Pop Stand',
    Ten80_Stance: 'Ten80 Stance',
    Ten80_Top_Freeze: 'Ten80 Top Freeze',
    Ten80_Top_L_Step: 'Ten80 Top L Step',
    Ten80_Top_R_Cross: 'Ten80 Top R Cross',
    Ten80_Top_R_Step: 'Ten80 Top R Step',
    Ten80_Top_Stand: 'Ten80 Top Stand',
    Tennisball: 'Tennisball',
    Teraa: 'Tera-a',
    Terab: 'Tera-b',
    Terac: 'Tera-c',
    Terad: 'Tera-d',
    Toucana: 'Toucan-a',
    Toucanb: 'Toucan-b',
    Toucanc: 'Toucan-c',
    Trampoline: 'Trampoline',
    Tree1: 'Tree1',
    Treesa: 'Trees-a',
    Treesb: 'Trees-b',
    Trishaa: 'Trisha-a',
    Trishab: 'Trisha-b',
    Trishac: 'Trisha-c',
    Trishad: 'Trisha-d',
    Trucka: 'Truck-a',
    Truckb: 'Truck-b',
    Truckc: 'Truck-c',
    Trumpeta: 'Trumpet-a',
    Trumpetb: 'Trumpet-b',
    Unicorn: 'Unicorn',
    Unicorn_2: 'Unicorn 2',
    Unicorn_Runninga: 'Unicorn Running-a',
    Unicorn_Runningb: 'Unicorn Running-b',
    Unicorn_Runningc: 'Unicorn Running-c',
    Unicorn_Runningd: 'Unicorn Running-d',
    Unicorn_Runninge: 'Unicorn Running-e',
    Unicorn_Runningf: 'Unicorn Running-f',
    Wand: 'Wand',
    Wanda: 'Wanda',
    Watermelona: 'Watermelon-a',
    Watermelonb: 'Watermelon-b',
    Watermelonc: 'Watermelon-c',
    Winter_Hat: 'Winter Hat',
    Witch: 'Witch',
    Witcha: 'Witch-a',
    Witchb: 'Witch-b',
    Witchc: 'Witch-c',
    Witchd: 'Witch-d',
    Wizard_Girl: 'Wizard Girl',
    Wizard_Hat: 'Wizard Hat',
    Wizarda: 'Wizard-a',
    Wizardb: 'Wizard-b',
    Wizardc: 'Wizard-c',
    Wizardtoada: 'Wizard-toad-a',
    Wizardtoadb: 'Wizard-toad-b',
    Zebraa: 'Zebra-a',
    Zebrab: 'Zebra-b',
    Blocka: 'Block-a',
    Blockb: 'Block-b',
    Blockc: 'Block-c',
    Blockd: 'Block-d',
    Blocke: 'Block-e',
    Blockf: 'Block-f',
    Blockg: 'Block-g',
    Blockh: 'Block-h',
    Blocki: 'Block-i',
    Blockj: 'Block-j',
    Blockk: 'Block-k',
    Blockl: 'Block-l',
    Blockm: 'Block-m',
    Blockn: 'Block-n',
    Blocko: 'Block-o',
    Blockp: 'Block-p',
    Blockq: 'Block-q',
    Blockr: 'Block-r',
    Blocks: 'Block-s',
    Blockt: 'Block-t',
    Blocku: 'Block-u',
    Blockv: 'Block-v',
    Blockw: 'Block-w',
    Blockx: 'Block-x',
    Blocky: 'Block-y',
    Blockz: 'Block-z',
    Glow0: 'Glow-0',
    Glow1: 'Glow-1',
    Glow2: 'Glow-2',
    Glow3: 'Glow-3',
    Glow4: 'Glow-4',
    Glow5: 'Glow-5',
    Glow6: 'Glow-6',
    Glow7: 'Glow-7',
    Glow8: 'Glow-8',
    Glow9: 'Glow-9',
    GlowA: 'Glow-A',
    GlowB: 'Glow-B',
    GlowC: 'Glow-C',
    GlowD: 'Glow-D',
    GlowE: 'Glow-E',
    GlowF: 'Glow-F',
    GlowG: 'Glow-G',
    GlowH: 'Glow-H',
    GlowI: 'Glow-I',
    GlowJ: 'Glow-J',
    GlowK: 'Glow-K',
    GlowL: 'Glow-L',
    GlowM: 'Glow-M',
    GlowN: 'Glow-N',
    GlowO: 'Glow-O',
    GlowP: 'Glow-P',
    GlowQ: 'Glow-Q',
    GlowR: 'Glow-R',
    GlowS: 'Glow-S',
    GlowT: 'Glow-T',
    GlowU: 'Glow-U',
    GlowV: 'Glow-V',
    GlowW: 'Glow-W',
    GlowX: 'Glow-X',
    GlowY: 'Glow-Y',
    GlowZ: 'Glow-Z',
    storyA1: 'story-A-1',
    storyA2: 'story-A-2',
    storyA3: 'story-A-3',
    storyB1: 'story-B-1',
    storyB2: 'story-B-2',
    storyB3: 'story-B-3',
    storyC1: 'story-C-1',
    storyC2: 'story-C-2',
    storyC3: 'story-C-3',
    storyD1: 'story-D-1',
    storyD2: 'story-D-2',
    storyD3: 'story-D-3',
    storyE1: 'story-E-1',
    storyE2: 'story-E-2',
    storyE3: 'story-E-3',
    storyF1: 'story-F-1',
    storyF2: 'story-F-2',
    storyF3: 'story-F-3',
    storyG1: 'story-G-1',
    storyG2: 'story-G-2',
    storyG3: 'story-G-3',
    storyH1: 'story-H-1',
    storyH2: 'story-H-2',
    storyH3: 'story-H-3',
    storyI1: 'story-I-1',
    storyI2: 'story-I-2',
    storyI3: 'story-I-3',
    storyJ1: 'story-J-1',
    storyJ2: 'story-J-2',
    storyJ3: 'story-J-3',
    storyK1: 'story-K-1',
    storyK2: 'story-K-2',
    storyK3: 'story-K-3',
    storyL1: 'story-L-1',
    storyL2: 'story-L-2',
    storyL3: 'story-L-3',
    storyM1: 'story-M-1',
    storyM2: 'story-M-2',
    storyM3: 'story-M-3',
    storyN1: 'story-N-1',
    storyN2: 'story-N-2',
    storyN3: 'story-N-3',
    storyO1: 'story-O-1',
    storyO2: 'story-O-2',
    storyO3: 'story-O-3',
    storyP1: 'story-P-1',
    storyP2: 'story-P-2',
    storyP3: 'story-P-3',
    storyQ1: 'story-Q-1',
    storyQ2: 'story-Q-2',
    storyQ3: 'story-Q-3',
    storyR1: 'story-R-1',
    storyR2: 'story-R-2',
    storyR3: 'story-R-3',
    storyS1: 'story-S-1',
    storyS2: 'story-S-2',
    storyS3: 'story-S-3',
    storyT1: 'story-T-1',
    storyT2: 'story-T-2',
    storyT3: 'story-T-3',
    storyU1: 'story-U-1',
    storyU2: 'story-U-2',
    storyU3: 'story-U-3',
    storyV1: 'story-V-1',
    storyV2: 'story-V-2',
    storyV3: 'story-V-3',
    storyW1: 'story-W-1',
    storyW2: 'story-W-2',
    storyW3: 'story-W-3',
    storyX1: 'story-X-1',
    storyX2: 'story-X-2',
    storyX3: 'story-X-3',
    storyY1: 'story-Y-1',
    storyY2: 'story-Y-2',
    storyY3: 'story-Y-3',
    storyZ1: 'story-Z-1',
    storyZ2: 'story-Z-2',
    storyZ3: 'story-Z-3',
} as const;
export type TypeCostumeBankKey = keyof typeof CostumeBank;
export type TypeCostumeBankVal = typeof CostumeBank[TypeCostumeBankKey];
