export const SoundBank = {
    A_Bass: 'A Bass',
    A_Elec_Bass: 'A Elec Bass',
    A_Elec_Guitar: 'A Elec Guitar',
    A_Elec_Piano: 'A Elec Piano',
    A_Guitar: 'A Guitar',
    A_Minor_Ukulele: 'A Minor Ukulele',
    A_Piano: 'A Piano',
    A_Sax: 'A Sax',
    A_Trombone: 'A Trombone',
    A_Trumpet: 'A Trumpet',
    Afro_String: 'Afro String',
    Alert: 'Alert',
    Alien_Creak1: 'Alien Creak1',
    Alien_Creak2: 'Alien Creak2',
    B_Bass: 'B Bass',
    B_Elec_Bass: 'B Elec Bass',
    B_Elec_Guitar: 'B Elec Guitar',
    B_Elec_Piano: 'B Elec Piano',
    B_Guitar: 'B Guitar',
    B_Piano: 'B Piano',
    B_Sax: 'B Sax',
    B_Trombone: 'B Trombone',
    B_Trumpet: 'B Trumpet',
    Baa: 'Baa',
    Bark: 'Bark',
    Basketball_Bounce: 'Basketball Bounce',
    Bass_Beatbox: 'Bass Beatbox',
    Beat_Box1: 'Beat Box1',
    Beat_Box2: 'Beat Box2',
    Bell_Cymbal: 'Bell Cymbal',
    Bell_Toll: 'Bell Toll',
    Big_Boing: 'Big Boing',
    Bird: 'Bird',
    Birthday: 'Birthday',
    Bite: 'Bite',
    Boing: 'Boing',
    Bonk: 'Bonk',
    Boom_Cloud: 'Boom Cloud',
    Boop_Bing_Bop: 'Boop Bing Bop',
    Bossa_Nova: 'Bossa Nova',
    Bowling_Strike: 'Bowling Strike',
    Bubbles: 'Bubbles',
    Buzz_Whir: 'Buzz Whir',
    C_Bass: 'C Bass',
    C_Elec_Bass: 'C Elec Bass',
    C_Elec_Guitar: 'C Elec Guitar',
    C_Elec_Piano: 'C Elec Piano',
    C_Guitar: 'C Guitar',
    C_Major_Ukulele: 'C Major Ukulele',
    C_Piano: 'C Piano',
    C_Sax: 'C Sax',
    C_Trombone: 'C Trombone',
    C_Trumpet: 'C Trumpet',
    C2_Bass: 'C2 Bass',
    C2_Elec_Bass: 'C2 Elec Bass',
    C2_Elec_Guitar: 'C2 Elec Guitar',
    C2_Elec_Piano: 'C2 Elec Piano',
    C2_Guitar: 'C2 Guitar',
    C2_Piano: 'C2 Piano',
    C2_Sax: 'C2 Sax',
    C2_Trombone: 'C2 Trombone',
    C2_Trumpet: 'C2 Trumpet',
    Car_Horn: 'Car Horn',
    Car_Passing: 'Car Passing',
    Car_Vroom: 'Car Vroom',
    Cave: 'Cave',
    Chatter: 'Chatter',
    Chee_Chee: 'Chee Chee',
    Cheer: 'Cheer',
    Chill: 'Chill',
    Chirp: 'Chirp',
    Chomp: 'Chomp',
    Chord: 'Chord',
    Clang: 'Clang',
    Clap_Beatbox: 'Clap Beatbox',
    Clapping: 'Clapping',
    Classical_Piano: 'Classical Piano',
    Clock_Ticking: 'Clock Ticking',
    Clown_Honk: 'Clown Honk',
    Coin: 'Coin',
    Collect: 'Collect',
    Computer_Beep: 'Computer Beep',
    Computer_Beep2: 'Computer Beep2',
    Connect: 'Connect',
    Cough1: 'Cough1',
    Cough2: 'Cough2',
    Crank: 'Crank',
    Crash_Beatbox: 'Crash Beatbox',
    Crash_Cymbal: 'Crash Cymbal',
    Crazy_Laugh: 'Crazy Laugh',
    Cricket: 'Cricket',
    Crickets: 'Crickets',
    Croak: 'Croak',
    Crowd_Gasp: 'Crowd Gasp',
    Crowd_Laugh: 'Crowd Laugh',
    Crunch: 'Crunch',
    Cymbal: 'Cymbal',
    Cymbal_Crash: 'Cymbal Crash',
    Cymbal_Echo: 'Cymbal Echo',
    D_Bass: 'D Bass',
    D_Elec_Bass: 'D Elec Bass',
    D_Elec_Guitar: 'D Elec Guitar',
    D_Elec_Piano: 'D Elec Piano',
    D_Guitar: 'D Guitar',
    D_Piano: 'D Piano',
    D_Sax: 'D Sax',
    D_Trombone: 'D Trombone',
    D_Trumpet: 'D Trumpet',
    Dance_Around: 'Dance Around',
    Dance_Celebrate: 'Dance Celebrate',
    Dance_Chill_Out: 'Dance Chill Out',
    Dance_Energetic: 'Dance Energetic',
    Dance_Funky: 'Dance Funky',
    Dance_Head_Nod: 'Dance Head Nod',
    Dance_Magic: 'Dance Magic',
    Dance_Sitar: 'Dance Sitar',
    Dance_Slow_Mo: 'Dance Slow Mo',
    Dance_Snare_Beat: 'Dance Snare Beat',
    Dance_Space: 'Dance Space',
    Disconnect: 'Disconnect',
    Dog1: 'Dog1',
    Dog2: 'Dog2',
    Door_Closing: 'Door Closing',
    Door_Creak: 'Door Creak',
    Doorbell: 'Doorbell',
    Drip_Drop: 'Drip Drop',
    Drive_Around: 'Drive Around',
    Drum: 'Drum',
    Drum_Bass1: 'Drum Bass1',
    Drum_Bass2: 'Drum Bass2',
    Drum_Bass3: 'Drum Bass3',
    Drum_Boing: 'Drum Boing',
    Drum_Buzz: 'Drum Buzz',
    Drum_Funky: 'Drum Funky',
    Drum_Jam: 'Drum Jam',
    Drum_Machine: 'Drum Machine',
    Drum_Roll: 'Drum Roll',
    Drum_Satellite: 'Drum Satellite',
    Drum_Set1: 'Drum Set1',
    Drum_Set2: 'Drum Set2',
    Dubstep: 'Dubstep',
    Duck: 'Duck',
    Dun_Dun_Dunnn: 'Dun Dun Dunnn',
    E_Bass: 'E Bass',
    E_Elec_Bass: 'E Elec Bass',
    E_Elec_Guitar: 'E Elec Guitar',
    E_Elec_Piano: 'E Elec Piano',
    E_Guitar: 'E Guitar',
    E_Piano: 'E Piano',
    E_Sax: 'E Sax',
    E_Trombone: 'E Trombone',
    E_Trumpet: 'E Trumpet',
    Eggs: 'Eggs',
    Elec_Piano_A_Minor: 'Elec Piano A Minor',
    Elec_Piano_C_Major: 'Elec Piano C Major',
    Elec_Piano_F_Major: 'Elec Piano F Major',
    Elec_Piano_G_Major: 'Elec Piano G Major',
    Elec_Piano_Loop: 'Elec Piano Loop',
    Emotional_Piano: 'Emotional Piano',
    Engine: 'Engine',
    F_Bass: 'F Bass',
    F_Elec_Bass: 'F Elec Bass',
    F_Elec_Guitar: 'F Elec Guitar',
    F_Elec_Piano: 'F Elec Piano',
    F_Guitar: 'F Guitar',
    F_Major_Ukulele: 'F Major Ukulele',
    F_Piano: 'F Piano',
    F_Sax: 'F Sax',
    F_Trombone: 'F Trombone',
    F_Trumpet: 'F Trumpet',
    Fairydust: 'Fairydust',
    Finger_Snap: 'Finger Snap',
    Flam_Snare: 'Flam Snare',
    Footsteps: 'Footsteps',
    G_Bass: 'G Bass',
    G_Elec_Bass: 'G Elec Bass',
    G_Elec_Guitar: 'G Elec Guitar',
    G_Elec_Piano: 'G Elec Piano',
    G_Guitar: 'G Guitar',
    G_Piano: 'G Piano',
    G_Sax: 'G Sax',
    G_Trombone: 'G Trombone',
    G_Trumpet: 'G Trumpet',
    G_Ukulele: 'G Ukulele',
    Gallop: 'Gallop',
    Garden: 'Garden',
    Glass_Breaking: 'Glass Breaking',
    Glug: 'Glug',
    Goal_Cheer: 'Goal Cheer',
    Gong: 'Gong',
    Goose: 'Goose',
    Growl: 'Growl',
    Grunt: 'Grunt',
    Guitar_Chords1: 'Guitar Chords1',
    Guitar_Chords2: 'Guitar Chords2',
    Guitar_Strum: 'Guitar Strum',
    Hand_Clap: 'Hand Clap',
    Head_Shake: 'Head Shake',
    Hey: 'Hey',
    Hi_Beatbox: 'Hi Beatbox',
    Hi_Na_Tabla: 'Hi Na Tabla',
    Hi_Tun_Tabla: 'Hi Tun Tabla',
    High_Conga: 'High Conga',
    High_Hat: 'High Hat',
    High_Tom: 'High Tom',
    High_Whoosh: 'High Whoosh',
    Hihat_Beatbox: 'Hihat Beatbox',
    Hihat_Cymbal: 'Hihat Cymbal',
    Hip_Hop: 'Hip Hop',
    Horse: 'Horse',
    Horse_Gallop: 'Horse Gallop',
    Human_Beatbox1: 'Human Beatbox1',
    Human_Beatbox2: 'Human Beatbox2',
    Jump: 'Jump',
    Jungle: 'Jungle',
    Jungle_Frogs: 'Jungle Frogs',
    Kick_Back: 'Kick Back',
    Kick_Drum: 'Kick Drum',
    Large_Cowbell: 'Large Cowbell',
    Laser1: 'Laser1',
    Laser2: 'Laser2',
    Laugh1: 'Laugh1',
    Laugh2: 'Laugh2',
    Laugh3: 'Laugh3',
    Lo_Geh_Tabla: 'Lo Geh Tabla',
    Lo_Gliss_Tabla: 'Lo Gliss Tabla',
    Lose: 'Lose',
    Low_Boing: 'Low Boing',
    Low_Conga: 'Low Conga',
    Low_Squeak: 'Low Squeak',
    Low_Tom: 'Low Tom',
    Low_Whoosh: 'Low Whoosh',
    Machine: 'Machine',
    Magic_Spell: 'Magic Spell',
    Medieval1: 'Medieval1',
    Medieval2: 'Medieval2',
    Meow: 'Meow',
    Meow2: 'Meow2',
    Moo: 'Moo',
    Motorcycle_Passing: 'Motorcycle Passing',
    Movie_1: 'Movie 1',
    Movie_2: 'Movie 2',
    Muted_Conga: 'Muted Conga',
    Mystery: 'Mystery',
    Ocean_Wave: 'Ocean Wave',
    Odesong: 'Odesong',
    Oops: 'Oops',
    Orchestra_Tuning: 'Orchestra Tuning',
    Owl: 'Owl',
    Party_Noise: 'Party Noise',
    Pew: 'Pew',
    Ping_Pong_Hit: 'Ping Pong Hit',
    Pluck: 'Pluck',
    Plunge: 'Plunge',
    Police_Siren: 'Police Siren',
    Pop: 'Pop',
    Rain: 'Rain',
    Rattle: 'Rattle',
    Referee_Whistle: 'Referee Whistle',
    Reggae: 'Reggae',
    Ricochet: 'Ricochet',
    Ride_Cymbal: 'Ride Cymbal',
    Ring_Tone: 'Ring Tone',
    Rip: 'Rip',
    Ripples: 'Ripples',
    Roll_Cymbal: 'Roll Cymbal',
    Rooster: 'Rooster',
    Scrambling_Feet: 'Scrambling Feet',
    Scratch_Beatbox: 'Scratch Beatbox',
    Scratchy_Beat: 'Scratchy Beat',
    Scream1: 'Scream1',
    Scream2: 'Scream2',
    Screech: 'Screech',
    Seagulls: 'Seagulls',
    Sewing_Machine: 'Sewing Machine',
    Shaker: 'Shaker',
    Ship_Bell: 'Ship Bell',
    Sidestick_Snare: 'Sidestick Snare',
    Singer1: 'Singer1',
    Singer2: 'Singer2',
    Siren_Whistle: 'Siren Whistle',
    Skid: 'Skid',
    Slide_Whistle: 'Slide Whistle',
    Small_Cowbell: 'Small Cowbell',
    Snap: 'Snap',
    Snare_Beatbox: 'Snare Beatbox',
    Snare_Beatbox2: 'Snare Beatbox2',
    Snare_Drum: 'Snare Drum',
    Sneaker_Squeak: 'Sneaker Squeak',
    Sneeze1: 'Sneeze1',
    Sneeze2: 'Sneeze2',
    Snoring: 'Snoring',
    Snort: 'Snort',
    Space_Ambience: 'Space Ambience',
    Space_Flyby: 'Space Flyby',
    Space_Noise: 'Space Noise',
    Space_Ripple: 'Space Ripple',
    Spiral: 'Spiral',
    Splash: 'Splash',
    Splash_Cymbal: 'Splash Cymbal',
    Spooky_String: 'Spooky String',
    Squawk: 'Squawk',
    Squeaks: 'Squeaks',
    Squeaky_Toy: 'Squeaky Toy',
    Squish_Pop: 'Squish Pop',
    String_Accent: 'String Accent',
    String_Pluck: 'String Pluck',
    Suction_Cup: 'Suction Cup',
    Suspense: 'Suspense',
    Tada: 'Tada',
    Tambura: 'Tambura',
    Tap_Conga: 'Tap Conga',
    Tap_Snare: 'Tap Snare',
    Techno: 'Techno',
    Techno2: 'Techno2',
    Telephone_Ring: 'Telephone Ring',
    Telephone_Ring2: 'Telephone Ring2',
    Teleport: 'Teleport',
    Teleport2: 'Teleport2',
    Teleport3: 'Teleport3',
    Tennis_Hit: 'Tennis Hit',
    Thunder_Storm: 'Thunder Storm',
    Tom_Drum: 'Tom Drum',
    Toy_Honk: 'Toy Honk',
    Toy_Zing: 'Toy Zing',
    Traffic: 'Traffic',
    Train_Whistle: 'Train Whistle',
    Trap_Beat: 'Trap Beat',
    Triumph: 'Triumph',
    Tropical_Birds: 'Tropical Birds',
    Trumpet1: 'Trumpet1',
    Trumpet2: 'Trumpet2',
    Video_Game_1: 'Video Game 1',
    Video_Game_2: 'Video Game 2',
    Wah_Beatbox: 'Wah Beatbox',
    Wand: 'Wand',
    Water_Drop: 'Water Drop',
    Whinny: 'Whinny',
    Whistle_Thump: 'Whistle Thump',
    Whiz: 'Whiz',
    Whoop: 'Whoop',
    Win: 'Win',
    Wobble: 'Wobble',
    Wolf_Howl: 'Wolf Howl',
    Wood_Tap: 'Wood Tap',
    Wub_Beatbox: 'Wub Beatbox',
    Xylo1: 'Xylo1',
    Xylo2: 'Xylo2',
    Xylo3: 'Xylo3',
    Xylo4: 'Xylo4',
    Ya: 'Ya',
    Zip: 'Zip',
    Zoop: 'Zoop',
} as const;
export type TypeSoundBankKey = keyof typeof SoundBank;
export type TypeSoundBankVal = typeof SoundBank[TypeSoundBankKey];